language: cpp
compiler: gcc
dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo bash -c "echo ttf-mssourcefonts-installer msttsourcefonts/accepted-mssourcefonts-eula select true | debconf-set-selections"
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-8 g++-8 cmake libcairo2-dev libharfbuzz-dev libfreetype6-dev msttsourcefonts ttf-mssourcefonts-installer
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
  - sudo fc-cache

script:
  - fc-match "Arial,Helvetica,Helvetica Neue:style=Regular,Roman"
  - cmake .
  - make all test CTEST_OUTPUT_ON_FAILURE=1
