language: cpp
compiler: gcc
dist: bionic

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-8 g++-8 cmake libfreetype6-dev libharfbuzz-dev libfribidi-dev libcairo2-dev libfmt-dev

script:
  - cmake .
  - make all
