language: cpp
compiler: gcc
dist: xenial

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-8 g++-8 cmake libcairo2-dev libharfbuzz-dev libfreetype6-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script:
  - cmake .
  - make all test CTEST_OUTPUT_ON_FAILURE=1
